### ISSUE TITLE
ConstraintViolation when one or more categories are disabled

### ISSUE THREAD

**Issue by sebastiancretu** [ConnectHolland/cookie-consent-bundle#17]
Hi,

When one or more categories are disabled from config, i get an constarint violation error in symfony. I attached the screenshot. Thanks
![2019-03-12_1746_001](https://user-images.githubusercontent.com/2368005/54214666-52e32080-44ef-11e9-99b3-e4da20f00f95.png)
Here is my config file:
`ch_cookie_consent:
  theme: 'light' # light, dark
  categories: # Below are the default supported categories
      - 'analytics'
      - 'marketing'
  use_logger: true # Logs user actions to database`

**Comment by matthijsch** [comment]
I can't seem to reproduce the problem. Does this error occur when submitting the form or when viewing the form?

**Comment by sebastiancretu** [comment]
Sorry for the delay. It happend when viewing the form.

**Comment by reyostallenberg** [comment]
This happens when you re-submit a form after adding a new field. You should always reload the page (with get) before (re-)submitting after a change of fields on the FormType. So: no bug of this bundle and therefor closing. 

If you think it is a bug of this bundle, please add a new issue with steps on how to reproduce your problem/issue.
